name: Notify

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      # From: https://github.com/SethCohen/github-releases-to-discord
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: "2105893"
          username: "D4LF Release"
